name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Simulate a Build
        run: echo 'hello youtube' > output.txt
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:          
          name: 'your-artifact-name'
          path: 'output.txt'
          
  create-issues:
    needs: [build]
    name: Create Deployment Issues
    runs-on: ubuntu-latest
    
    steps:
      - name: Create PROD Issue
        uses: JasonEtco/create-an-issue@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: Prod
          RUNNUMBER: ${{ github.run_number  }}
        with:         
          filename: .github/deployment-approval.md
          
      - name: Create ALT-PROD Issue
        uses: JasonEtco/create-an-issue@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: alt-prod
          RUNNUMBER: ${{ github.run_number  }}
        with:         
          filename: .github/deployment-approval.md
